runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /static/(.*)$
  static_files: static/\1
  upload: static/.*$

- url: /api/.*
  script: _go_app

builtins:
- appstats: on
